# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField(max_length=50)),
                ('issue_date', models.DateField()),
                ('issue_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'available'), ('unissued', 'unissued'), ('issued', 'issued'), ('returned', 'returned'), ('deadline_crossed', 'deadline_crossed')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('copies_avl', models.IntegerField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('student', 'student'), ('librarian', 'librarian')], max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookissue',
            name='Book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Books'),
        ),
    ]
