# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='summary',
            field=models.TextField(max_length=5000),
        ),
    ]
