# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180720_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='status',
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unissued', 'unissued'), ('issued', 'issued'), ('returned', 'returned'), ('deadline_crossed', 'deadline_crossed')], max_length=20, null=True),
        ),
    ]
