# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180721_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='issue_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='copies_avl',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unissued', 'unissued'), ('issued', 'issued'), ('returned', 'returned'), ('deadline_crossed', 'deadline_crossed')], default='available', max_length=20, null=True),
        ),
    ]
