# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180721_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='rollno',
        ),
    ]
