# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_bookissue_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='issue_time',
        ),
    ]
