# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180722_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='Book_name',
            new_name='Book',
        ),
    ]
