# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180722_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 7, 52, 12, 930410)),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 7, 52, 12, 930437)),
        ),
    ]
