# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180722_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('issued', 'issued'), ('returned', 'returned'), ('deadline_crossed', 'deadline_crossed')], default='booked', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 8, 9, 29, 842241)),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 8, 9, 29, 842265)),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20, null=True),
        ),
    ]
