# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180722_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='fine',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 12, 29, 21, 833508)),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 4, 12, 29, 21, 833530)),
        ),
    ]
